const QuestTypes = {
	goldMaxHoard: 0, goldTotalRecive: 1, heroLevelUp: 2, heroUpgrades: 3, dps: 4,
	clicksPerSec: 5, critPerSecond: 6, totalClicks: 7, zoneReach: 8, ascendCount: 9,
	killMonsters: 10, killBosses: 11, bountyBoss: 12, findRelic: 13, mercMaxLevel: 14,
	mercBury: 15, mercRevive: 16, AcquireAncientSouls: 17, beatZoneAfterTranscend: 18,
	q5Min: 19, qGold: 20, qHeroSouls: 21, qRuby: 22, qSkill: 23, qRelic: 24, treasureChest: 25
}, AchievementType = {
	Gold: 0, Hero: 1, DPS: 2, Click: 3, Zone: 4, Ascension: 5, Monster: 6, CentennialBoss: 7, Relic: 8, Mercenary: 9, Quests: 10, Transcendence: 11, Other: 12
},
	imagesURL = 'https://static.wikia.nocookie.net/clickerheroes/images/',
	AchievementsList = {
		1: ['Zone Explorer', 'Beat Zone 10.', undefined, undefined, 'f/f0/Zone_explorer.png', AchievementType.Zone, { type: QuestTypes.zoneReach, target: 10 }],
		2: ['Zone Warrior', 'Beat Zone 25.', undefined, undefined, 'f/f0/Zone_explorer.png', AchievementType.Zone, { type: QuestTypes.zoneReach, target: 25 }],
		3: ['Zone Master', 'Beat Zone 50.', undefined, undefined, 'f/f0/Zone_explorer.png', AchievementType.Zone, { type: QuestTypes.zoneReach, target: 50 }],
		4: ['Zone Lord', 'Beat Zone 100.', undefined, undefined, 'f/f0/Zone_explorer.png', AchievementType.Zone, { type: QuestTypes.zoneReach, target: 100 }],
		5: ['Proficient Clicking', 'Click 1,000 times.', undefined, undefined, 'f/f5/Proficient_Clicking.png', AchievementType.Click, { type: QuestTypes.totalClicks, target: 1e3 }],
		6: ['Sore Finger', 'Click 10,000 times.', undefined, undefined, '0/02/Sore_Finger.png', AchievementType.Click, { type: QuestTypes.totalClicks, target: 1e4 }],
		7: ['Carpal Tunnel', 'Click 50,000 times.', undefined, undefined, '5/55/Carpal_Tunnel.png', AchievementType.Click, { type: QuestTypes.totalClicks, target: 5e4 }],
		8: ['Broken Mouse', 'Click 100K times.', 'RIP in peace, mouse.', undefined, '3/3a/Broken_Mouse.png', AchievementType.Click, { type: QuestTypes.totalClicks, target: 1e5 }],
		9: ['Uptown', 'Receive (cumulative) 1.000e6 gold.', undefined, undefined, '3/36/Uptown.png', AchievementType.Gold, { type: QuestTypes.goldTotalRecive, target: 1e6 }],
		10: ['Fat Cat', 'Receive (cumulative) 1.000e9 gold.', undefined, undefined, 'c/ca/Fat_Cat.png', AchievementType.Gold, { type: QuestTypes.goldTotalRecive, target: 1e9 }],
		11: ['Loaded', 'Receive (cumulative) 1.000e15 gold.', undefined, undefined, '2/2b/Loaded.png', AchievementType.Gold, { type: QuestTypes.goldTotalRecive, target: 1e15 }],
		12: ['The 1%', 'Receive (cumulative) 1.000e20 gold.', undefined, undefined, '1/1b/The_1%25.png', AchievementType.Gold, { type: QuestTypes.goldTotalRecive, target: 1e20 }],
		13: ['Frugal', 'Hoard 5.000e5 gold.', undefined, undefined, '0/0e/Frugal.png', AchievementType.Gold, { type: QuestTypes.goldMaxHoard, target: 5e5 }],
		14: ['Stingy', 'Hoard 5.000e12 gold.', undefined, undefined, '0/07/Stingy.png', AchievementType.Gold, { type: QuestTypes.goldMaxHoard, target: 5e12 }],
		15: ['Miserly', 'Hoard 5.000e20 gold.', undefined, undefined, '9/94/Miserly.png', AchievementType.Gold, { type: QuestTypes.goldMaxHoard, target: 5e20 }],
		16: ['Greedy', 'Hoard 5.000e31 gold.', undefined, undefined, 'a/aa/Greedy.png', AchievementType.Gold, { type: QuestTypes.goldMaxHoard, target: 5e31 }],
		17: ['Killer', 'Kill 100 monsters.', undefined, undefined, '8/8e/Killer.png', AchievementType.Monster, { type: QuestTypes.killMonsters, target: 100 }],
		18: ['Butcher', 'Kill 1,000 monsters.', undefined, undefined, 'f/fb/Butcher.png', AchievementType.Monster, { type: QuestTypes.killMonsters, target: 1000 }],
		19: ['Executioner', 'Kill 10,000 monsters.', undefined, undefined, '1/15/Executionner.png', AchievementType.Monster, { type: QuestTypes.killMonsters, target: 10000 }],
		20: ['Monster Genocide', 'Kill 1.000e5 monsters.', undefined, undefined, '4/49/Holocaust.png', AchievementType.Monster, { type: QuestTypes.killMonsters, target: 1e5 }],
		21: ['Boss Slaughter', 'Kill 10 bosses.', undefined, undefined, '2/28/Boss_Slaughter.png', AchievementType.Monster, { type: QuestTypes.killBosses, target: 10 }],
		22: ['Boss Massacre', 'Kill 100 bosses.', undefined, undefined, 'b/b6/Boss_Massacre.png', AchievementType.Monster, { type: QuestTypes.killBosses, target: 1e2 }],
		23: ['Boss Exterminator', 'Kill 1,000 bosses.', undefined, undefined, '5/53/Boss_Exterminator.png', AchievementType.Monster, { type: QuestTypes.killBosses, target: 1e3 }],
		24: ['Boss Murderer', 'Kill 10,000 bosses.', undefined, undefined, '7/7a/Boss_Murderer.png', AchievementType.Monster, { type: QuestTypes.killBosses, target: 1e4 }],
		25: ['Considerate', 'Get 25 hero upgrades.', undefined, undefined, '1/12/Considerate.png', AchievementType.Hero, { type: QuestTypes.heroUpgrades, target: 25 }],
		26: ['Generous', 'Get 50 hero upgrades.', undefined, undefined, '4/4b/Generous.png', AchievementType.Hero, { type: QuestTypes.heroUpgrades, target: 50 }],
		27: ['Benevolent', 'Get 100 hero upgrades.', undefined, undefined, 'b/b3/Benevolent.png', AchievementType.Hero, { type: QuestTypes.heroUpgrades, target: 100 }],
		28: ['Magnanimous', 'Get 200 hero upgrades.', undefined, undefined, 'f/f2/Magnanimous.png', AchievementType.Hero, { type: QuestTypes.heroUpgrades, target: 200 }],
		29: ['Guide', 'Level up heroes 100 times.', undefined, undefined, '7/7f/Guide.png', AchievementType.Hero, { type: QuestTypes.heroLevelUp, target: 100 }],
		30: ['Coach', 'Level up heroes 500 times.', undefined, undefined, '9/9d/Coach.png', AchievementType.Hero, { type: QuestTypes.heroLevelUp, target: 500 }],
		31: ['Teacher', 'Level up heroes 2500 times.', undefined, undefined, '6/6f/Teacher.png', AchievementType.Hero, { type: QuestTypes.heroLevelUp, target: 2500 }],
		32: ['Mentor', 'Level up heroes 10000 times.', undefined, undefined, 'c/c2/Mentor.png', AchievementType.Hero, { type: QuestTypes.heroLevelUp, target: 1e4 }],
		33: ['Lethal', 'Reach 1.000e7 DPS.', undefined, undefined, '1/13/Lethal.png', AchievementType.DPS, { type: QuestTypes.dps, target: 1e7 }],
		34: ['Ruinous', 'Reach 1.000e11 DPS.', undefined, undefined, '0/0f/Ruinous.png', AchievementType.DPS, { type: QuestTypes.dps, target: 1e11 }],
		35: ['Calamitous', 'Reach 1.000e16 DPS.', undefined, undefined, '0/01/Calamitous.png', AchievementType.DPS, { type: QuestTypes.dps, target: 1e16 }],
		36: ['Cataclysmic', 'Reach 1.000e21 DPS.', undefined, undefined, '5/5b/Cataclysmic.png', AchievementType.DPS, { type: QuestTypes.dps, target: 1e21 }],
		37: ['Frantic', 'Click 12 times in one second.', undefined, '+1 Click Damage', 'b/b6/Frantic.png', AchievementType.Click, { type: QuestTypes.clicksPerSec, target: 12 }],
		38: ['Frenetic', 'Click 14 times in one second.', undefined, '+3 Click Damage', 'c/c6/Frenetic.png', AchievementType.Click, { type: QuestTypes.clicksPerSec, target: 14 }],
		39: ['Frenzied', 'Click 25 times in one second.', undefined, undefined, '4/4c/Frenzied.png', AchievementType.Click, { type: QuestTypes.clicksPerSec, target: 25 }],
		40: ['Convulsions', 'Click 35 times in one second.', undefined, undefined, 'b/b5/Convulsions.png', AchievementType.Click, { type: QuestTypes.clicksPerSec, target: 35 }],
		41: ['Deadly', 'Get 2 Critical Clicks in one second.', undefined, undefined, 'b/b6/Frantic.png', AchievementType.Click, { type: QuestTypes.critPerSecond, target: 2 }],
		42: ['Assassin', 'Get 10 Critical Clicks in one second.', undefined, undefined, 'b/b5/Convulsions.png', AchievementType.Click, { type: QuestTypes.critPerSecond, target: 10 }],
		43: ['Restarter', 'Ascend the world 1 time.', undefined, '+10 Starting Click Damage.', 'f/f0/Zone_explorer.png', AchievementType.Ascension, { type: QuestTypes.ascendCount, target: 1 }],
		44: ['Neverending', 'Ascend the world 3 time.', undefined, '+50 Starting Click Damage.', '1/1b/Zone_Warrior.png', AchievementType.Ascension, { type: QuestTypes.ascendCount, target: 3 }],
		45: ['Again and Again', 'Ascend the world 5 time.', undefined, '+250 Starting Click Damage.', '7/72/Again_and_Again.png', AchievementType.Ascension, { type: QuestTypes.ascendCount, target: 5 }],
		46: ['Is this real life?', 'Ascend the world 10 time.', undefined, '+1000 Starting Click Damage.', 'a/ae/Zone_Lord.png', AchievementType.Ascension, { type: QuestTypes.ascendCount, target: 10 }],
		47: ['Zone King', 'Beat Zone 120.', undefined, undefined, 'f/f0/Zone_explorer.png', AchievementType.Zone, { type: QuestTypes.zoneReach, target: 120 }],
		48: ['Zone God', 'Beat Zone 140.', undefined, undefined, 'f/f0/Zone_explorer.png', AchievementType.Zone, { type: QuestTypes.zoneReach, target: 140 }],
		49: ['Zone Owner', 'Beat Zone 160.', undefined, undefined, 'f/f0/Zone_explorer.png', AchievementType.Zone, { type: QuestTypes.zoneReach, target: 160 }],
		50: ['The 0.01%', 'Receive (cumulative) 1.000e26 gold.', undefined, undefined, '1/1b/The_1%25.png', AchievementType.Gold, { type: QuestTypes.goldTotalRecive, target: 1e26 }],
		51: ['Buffett', 'Receive (cumulative) 1.000e32 gold.', undefined, undefined, '1/1b/The_1%25.png', AchievementType.Gold, { type: QuestTypes.goldTotalRecive, target: 1e32 }],
		52: ['Gates', 'Receive (cumulative) 1.000e38 gold.', undefined, undefined, '1/1b/The_1%25.png', AchievementType.Gold, { type: QuestTypes.goldTotalRecive, target: 1e38 }],
		53: ['Rockefeller', 'Receive (cumulative) 1.000e44 gold.', undefined, undefined, '1/1b/The_1%25.png', AchievementType.Gold, { type: QuestTypes.goldTotalRecive, target: 1e44 }],
		54: ['Terminator', 'Kill 1.000e6 monsters.', undefined, undefined, '4/49/Holocaust.png', AchievementType.Monster, { type: QuestTypes.killMonsters, target: 1e6 }],
		55: ['Boss Genocide', 'Kill 1.000e5 bosses.', undefined, undefined, '7/7a/Boss_Murderer.png', AchievementType.Monster, { type: QuestTypes.killBosses, target: 1e5 }],
		56: ['Levelupper', 'Level up heroes 25000 times.', undefined, undefined, 'c/c2/Mentor.png', AchievementType.Hero, { type: QuestTypes.heroLevelUp, target: 2.5e4 }],
		57: ['Super Levelupper', 'Level up heroes 50000 times.', undefined, undefined, 'c/c2/Mentor.png', AchievementType.Hero, { type: QuestTypes.heroLevelUp, target: 5e4 }],
		58: ['A lot of Damage', 'Reach 1.000e27 DPS.', undefined, undefined, '5/5b/Cataclysmic.png', AchievementType.DPS, { type: QuestTypes.dps, target: 1e27 }],
		59: ['Master of Reincarnation', 'Ascend the world 25 time.', undefined, '+2500 Starting Click Damage.', '9/95/Is_the_real_life.png', AchievementType.Ascension, { type: QuestTypes.ascendCount, target: 25 }],
		60: ['Treasure Hunter', 'Open 10,000 treasure chests', 'Swiggity swooty...', undefined, '1/1b/The_1%25.png', AchievementType.Other, { type: QuestTypes.treasureChest, target: 1e4 }],
		61: ['Bounty: Omeet', 'Defeat Omeet', 'How can one hamster be so hated throughout the land?', undefined, '7/7a/Boss_Murderer.png', AchievementType.CentennialBoss, { type: QuestTypes.bountyBoss, target: 1 }],
		62: ['Bounty: The Green One', 'Defeat the Green One', undefined, undefined, '7/7a/Boss_Murderer.png', AchievementType.CentennialBoss, { type: QuestTypes.bountyBoss, target: 1 }],
		63: ['Bounty: Woodchip, the Rodent', 'Defeat Woodchip, the Rodent', 'He used to be a Kung Fu master, but he really let himself go. Probably one too many pizzas.', undefined, '7/7a/Boss_Murderer.png', AchievementType.CentennialBoss, { type: QuestTypes.bountyBoss, target: 1 }],
		64: ['Bounty: Queen of Bloops', 'Defeat the Queen of Bloops', 'She\'s very angry that you\'ve been smashing her babies.', undefined, '7/7a/Boss_Murderer.png', AchievementType.CentennialBoss, { type: QuestTypes.bountyBoss, target: 1 }],
		65: ['Bounty: Doppler, the Robot', 'Defeat Doppler, the Robot', undefined, undefined, '7/7a/Boss_Murderer.png', AchievementType.CentennialBoss, { type: QuestTypes.bountyBoss, target: 1 }],
		66: ['Bounty: Rashon, the Duke', 'Defeat Rashon, the Duke', 'Once an Ancient, Duke Rashon became mortal when a group of 5 adventurers stole his Aegis. Good thing, too, because he\'s standing in your way of getting this achievement.', undefined, '7/7a/Boss_Murderer.png', AchievementType.CentennialBoss, { type: QuestTypes.bountyBoss, target: 1 }],
		67: ['Bounty: The Dark Wizard', 'Defeat the Dark Wizard', 'A legendary boss from another realm, he\'s here on a secret mission.', undefined, '7/7a/Boss_Murderer.png', AchievementType.CentennialBoss, { type: QuestTypes.bountyBoss, target: 1 }],
		68: ['Bounty: Tako, Head of the Octopi', 'Defeat Tako, Head of the Octopi', 'He\'ll probably come back if you kill him.', undefined, '7/7a/Boss_Murderer.png', AchievementType.CentennialBoss, { type: QuestTypes.bountyBoss, target: 1 }],
		69: ['Bounty: Tako Returns', 'Defeat Tako, again', 'This isn\'t even his final form.', undefined, '7/7a/Boss_Murderer.png', AchievementType.CentennialBoss, { type: QuestTypes.bountyBoss, target: 1 }],
		70: ['Bounty: Lagomorph of Caerbannog', 'Defeat the Lagomorph of Caerbannog', undefined, undefined, '7/7a/Boss_Murderer.png', AchievementType.CentennialBoss, { type: QuestTypes.bountyBoss, target: 1 }],
		71: ['Finger Amputee', 'Click 250K times.', undefined, undefined, '3/3a/Broken_Mouse.png', AchievementType.Click, { type: QuestTypes.totalClicks, target: 2.5e5 }],
		72: ['Mass Murderer', 'Kill 1.500e6 monsters.', undefined, undefined, '4/49/Holocaust.png', AchievementType.Monster, { type: QuestTypes.killMonsters, target: 1.5e6 }],
		73: ['Too Stronk', 'Reach 1.000e31 DPS.', undefined, undefined, '5/5b/Cataclysmic.png', AchievementType.DPS, { type: QuestTypes.dps, target: 1e31 }],
		74: ['You lift?', 'Reach 1.000e37 DPS.', undefined, undefined, '5/5b/Cataclysmic.png', AchievementType.DPS, { type: QuestTypes.dps, target: 1e37 }],
		75: ['Leg days skipped: 0', 'Reach 1.000e43 DPS.', undefined, undefined, '5/5b/Cataclysmic.png', AchievementType.DPS, { type: QuestTypes.dps, target: 1e43 }],
		76: ['Unreal Power', 'Reach 1.000e49 DPS.', undefined, undefined, '5/5b/Cataclysmic.png', AchievementType.DPS, { type: QuestTypes.dps, target: 1e49 }],
		77: ['Worlds Strongest', 'Reach 1.000e55 DPS.', undefined, undefined, '5/5b/Cataclysmic.png', AchievementType.DPS, { type: QuestTypes.dps, target: 1e55 }],
		78: ['Money Ain\'t A Thang', 'Receive (cumulative) 1.000e50 gold.', undefined, undefined, '1/1b/The_1%25.png', AchievementType.Gold, { type: QuestTypes.goldTotalRecive, target: 1e50 }],
		79: ['Money Tree', 'Receive (cumulative) 1.000e56 gold.', undefined, undefined, '1/1b/The_1%25.png', AchievementType.Gold, { type: QuestTypes.goldTotalRecive, target: 1e56 }],
		80: ['Gold Hoarder', 'Receive (cumulative) 1.000e62 gold.', undefined, undefined, '1/1b/The_1%25.png', AchievementType.Gold, { type: QuestTypes.goldTotalRecive, target: 1e62 }],
		81: ['Super Rich', 'Receive (cumulative) 1.000e68 gold.', undefined, undefined, '1/1b/The_1%25.png', AchievementType.Gold, { type: QuestTypes.goldTotalRecive, target: 1e68 }],
		82: ['Filthy Rich', 'Receive (cumulative) 1.000e74 gold.', undefined, undefined, '1/1b/The_1%25.png', AchievementType.Gold, { type: QuestTypes.goldTotalRecive, target: 1e74 }],
		83: ['Zone Pwn', 'Beat Zone 1,200.', undefined, undefined, 'f/f0/Zone_explorer.png', AchievementType.Zone, { type: QuestTypes.zoneReach, target: 1200 }],
		84: ['Zoner', 'Beat Zone 1,400.', undefined, undefined, 'f/f0/Zone_explorer.png', AchievementType.Zone, { type: QuestTypes.zoneReach, target: 1400 }],
		85: ['Zone Pro', 'Beat Zone 1,600.', undefined, undefined, 'f/f0/Zone_explorer.png', AchievementType.Zone, { type: QuestTypes.zoneReach, target: 1600 }],
		86: ['Zone Crusher', 'Beat Zone 1,800.', undefined, undefined, 'f/f0/Zone_explorer.png', AchievementType.Zone, { type: QuestTypes.zoneReach, target: 1800 }],
		87: ['Zone Connoisseur', 'Beat Zone 2,000.', undefined, undefined, 'f/f0/Zone_explorer.png', AchievementType.Zone, { type: QuestTypes.zoneReach, target: 2000 }],
		88: ['Zone Annihilator', 'Beat Zone 2,200.', undefined, undefined, 'f/f0/Zone_explorer.png', AchievementType.Zone, { type: QuestTypes.zoneReach, target: 2200 }],
		89: ['End Zone', 'Beat Zone 2,400.', undefined, undefined, 'f/f0/Zone_explorer.png', AchievementType.Zone, { type: QuestTypes.zoneReach, target: 2400 }],
		90: ['Zoned Out', 'Beat Zone 2,600.', undefined, undefined, 'f/f0/Zone_explorer.png', AchievementType.Zone, { type: QuestTypes.zoneReach, target: 2600 }],
		91: ['Renew', 'Ascend the world 50 time.', undefined, '+5000 Starting Click Damage.', '9/95/Is_the_real_life.png', AchievementType.Ascension, { type: QuestTypes.ascendCount, target: 50 }],
		92: ['Out with the old and in with the new...again.', 'Ascend the world 100 time.', undefined, '+10000 Starting Click Damage.', '9/95/Is_the_real_life.png', AchievementType.Ascension, { type: QuestTypes.ascendCount, target: 100 }],
		93: ['Goodbye Cruel World', 'Ascend the world 250 time.', undefined, '+25000 Starting Click Damage.', '9/95/Is_the_real_life.png', AchievementType.Ascension, { type: QuestTypes.ascendCount, target: 250 }],
		94: ['Zowned', 'Beat Zone 2,800.', undefined, undefined, 'f/f0/Zone_explorer.png', AchievementType.Zone, { type: QuestTypes.zoneReach, target: 2800 }],
		95: ['Z 3000', 'Beat Zone 3,000.', undefined, undefined, 'f/f0/Zone_explorer.png', AchievementType.Zone, { type: QuestTypes.zoneReach, target: 3000 }],
		96: ['Zone Devourer', 'Beat Zone 3,200.', undefined, undefined, 'f/f0/Zone_explorer.png', AchievementType.Zone, { type: QuestTypes.zoneReach, target: 3200 }],
		97: ['Are We There Yet?', 'Beat Zone 3,400.', undefined, undefined, 'f/f0/Zone_explorer.png', AchievementType.Zone, { type: QuestTypes.zoneReach, target: 3400 }],
		98: ['Zone Conqueror', 'Beat Zone 3,600.', undefined, undefined, 'f/f0/Zone_explorer.png', AchievementType.Zone, { type: QuestTypes.zoneReach, target: 3600 }],
		99: ['Finders Keepers', 'Find 1 Relics.', undefined, undefined, '1/14/066.png', AchievementType.Relic, { type: QuestTypes.findRelic, target: 1 }],
		100: ['Oooh Shiny!', 'Find 10 Relics.', undefined, undefined, '1/14/066.png', AchievementType.Relic, { type: QuestTypes.findRelic, target: 10 }],
		101: ['Relic Hunter', 'Find 25 Relics.', undefined, undefined, '1/14/066.png', AchievementType.Relic, { type: QuestTypes.findRelic, target: 25 }],
		102: ['Relic Hoarder', 'Find 50 Relics.', undefined, undefined, '1/14/066.png', AchievementType.Relic, { type: QuestTypes.findRelic, target: 50 }],
		103: ['The Collector', 'Find 1000 Relics.', 'How did you find so many?', undefined, '1/14/066.png', AchievementType.Relic, { type: QuestTypes.findRelic, target: 1000 }],
		104: ['Mourner', 'Bury 5 Mercenaries.', undefined, undefined, '8/85/101_achieve.png', AchievementType.Mercenary, { type: QuestTypes.mercBury, target: 5 }],
		105: ['Gravedigger', 'Bury 25 Mercenaries.', undefined, undefined, '0/0a/25mercachieve.png', AchievementType.Mercenary, { type: QuestTypes.mercBury, target: 25 }],
		106: ['Undertaker', 'Bury 100 Mercenaries.', undefined, undefined, 'a/a7/100merc_achie.png', AchievementType.Mercenary, { type: QuestTypes.mercBury, target: 100 }],
		107: ['Funeral Director', 'Bury 200 Mercenaries.', undefined, undefined, '4/44/200merc_achie.png', AchievementType.Mercenary, { type: QuestTypes.mercBury, target: 200 }],
		108: ['Lifeguard', 'Revive 5 mercenaries', undefined, undefined, '7/74/5mercR_achie.png', AchievementType.Mercenary, { type: QuestTypes.mercRevive, target: 5 }],
		109: ['Resuscitator', 'Revive 25 mercenaries', undefined, undefined, 'f/fb/25mercR_achie.png', AchievementType.Mercenary, { type: QuestTypes.mercRevive, target: 25 }],
		110: ['Medic', 'Revive 100 mercenaries', undefined, undefined, 'b/b5/100mercR_achie.png', AchievementType.Mercenary, { type: QuestTypes.mercRevive, target: 100 }],
		111: ['Surgeon', 'Revive 500 mercenaries', undefined, undefined, 'c/cd/200mercR_achie.png', AchievementType.Mercenary, { type: QuestTypes.mercRevive, target: 500 }],
		113: ['Supervisor', 'Complete 5 quests for gold.', undefined, undefined, '1/1b/The_1%25.png', AchievementType.Quests, { type: QuestTypes.qGold, target: 5 }],
		114: ['Assistant to the Regional Manager', 'Complete 25 quests for gold.', undefined, undefined, '0/0e/Frugal.png', AchievementType.Quests, { type: QuestTypes.qGold, target: 25 }],
		115: ['Corporate Raider', 'Complete 100 quests for gold.', undefined, undefined, '0/07/Stingy.png', AchievementType.Quests, { type: QuestTypes.qGold, target: 100 }],
		116: ['Robber Baron', 'Complete 500 quests for gold.', undefined, undefined, '9/94/Miserly.png', AchievementType.Quests, { type: QuestTypes.qGold, target: 500 }],
		117: ['The Big Cheese', 'Complete 2500 quests for gold.', undefined, undefined, 'a/aa/Greedy.png', AchievementType.Quests, { type: QuestTypes.qGold, target: 2500 }],
		118: ['Archaeology Student', 'Complete 5 quests for Relics.', undefined, undefined, '1/14/066.png', AchievementType.Quests, { type: QuestTypes.qRelic, target: 5 }],
		119: ['Archaeologist', 'Complete 25 quests for Relics.', undefined, undefined, '1/14/066.png', AchievementType.Quests, { type: QuestTypes.qRelic, target: 25 }],
		110: ['Museum Curator', 'Complete 100 quests for Relics.', undefined, undefined, '1/14/066.png', AchievementType.Quests, { type: QuestTypes.qRelic, target: 100 }],
		121: ['Acquisitions Inc.', 'Complete 500 quests for Relics.', undefined, undefined, '1/14/066.png', AchievementType.Quests, { type: QuestTypes.qRelic, target: 500 }],
		122: ['Collector Collector', 'Complete 2500 quests for Relics.', undefined, undefined, '1/14/066.png', AchievementType.Quests, { type: QuestTypes.qRelic, target: 2500 }],
		123: ['Seeing Red', 'Complete 5 quests for Rubies.', undefined, undefined, '2/24/041.png', AchievementType.Quests, { type: QuestTypes.qRuby, target: 5 }],
		124: ['The Red Baron', 'Complete 25 quests for Rubies.', undefined, undefined, '7/70/077.png', AchievementType.Quests, { type: QuestTypes.qRuby, target: 25 }],
		125: ['Red Tide', 'Complete 100 quests for Rubies.', undefined, undefined, 'b/b8/062.png', AchievementType.Quests, { type: QuestTypes.qRuby, target: 100 }],
		126: ['Red Sea', 'Complete 500 quests for Rubies.', undefined, undefined, 'b/b8/062.png', AchievementType.Quests, { type: QuestTypes.qRuby, target: 500 }],
		127: ['Red Planet', 'Complete 2500 quests for Rubies.', undefined, undefined, '8/86/078.png', AchievementType.Quests, { type: QuestTypes.qRuby, target: 2500 }],
		128: ['Some skills', 'Complete 5 quests for skills.', undefined, undefined, '1/18/006.png', AchievementType.Quests, { type: QuestTypes.qSkill, target: 5 }],
		129: ['A few more skills', 'Complete 25 quests for skills.', undefined, undefined, '5/5e/015.png', AchievementType.Quests, { type: QuestTypes.qSkill, target: 25 }],
		120: ['Kind of a lot of skills', 'Complete 100 quests for skills.', undefined, undefined, 'b/b0/047.png', AchievementType.Quests, { type: QuestTypes.qSkill, target: 100 }],
		131: ['Enitrely too many skills', 'Complete 500 quests for skills.', undefined, undefined, '1/18/006.png', AchievementType.Quests, { type: QuestTypes.qSkill, target: 500 }],
		132: ['Wow, really?', 'Complete 2500 quests for skills.', undefined, undefined, '3/3b/087.png', AchievementType.Quests, { type: QuestTypes.qSkill, target: 2500 }],
		133: ['Soul Taster', 'Complete 5 quests for Hero Souls.', undefined, undefined, '7/7f/Guide.png', AchievementType.Quests, { type: QuestTypes.qHeroSouls, target: 5 }],
		134: ['Soul Harvester', 'Complete 25 quests for Hero Souls.', undefined, undefined, '9/9d/Coach.png', AchievementType.Quests, { type: QuestTypes.qHeroSouls, target: 25 }],
		135: ['Soul Trader', 'Complete 100 quests for Hero Souls.', undefined, undefined, '6/6f/Teacher.png', AchievementType.Quests, { type: QuestTypes.qHeroSouls, target: 100 }],
		136: ['Soul Banker', 'Complete 500 quests for Hero Souls.', undefined, undefined, 'c/c2/Mentor.png', AchievementType.Quests, { type: QuestTypes.qHeroSouls, target: 500 }],
		137: ['Disciple of Solomon', 'Complete 2500 quests for Hero Souls.', undefined, undefined, '4/42/079.png', AchievementType.Quests, { type: QuestTypes.qHeroSouls, target: 2500 }],
		138: ['Short Work', 'Complete 10 5-minute quests.', undefined, undefined, '0/01/105.png', AchievementType.Quests, { type: QuestTypes.q5Min, target: 10 }],
		139: ['Running Late', 'Complete 50 5-minute quests.', undefined, undefined, '0/01/105.png', AchievementType.Quests, { type: QuestTypes.q5Min, target: 50 }],
		130: ['Overtime', 'Complete 250 5-minute quests.', undefined, undefined, '0/01/105.png', AchievementType.Quests, { type: QuestTypes.q5Min, target: 250 }],
		141: ['Doubletime', 'Complete 1000 5-minute quests.', undefined, undefined, '3/3a/106.png', AchievementType.Quests, { type: QuestTypes.q5Min, target: 1000 }],
		142: ['Micromanager', 'Complete 5000 5-minute quests.', undefined, undefined, '3/3a/106.png', AchievementType.Quests, { type: QuestTypes.q5Min, target: 5000 }],
		144: ['67.66 Repeating', 'Bury Leeroy Jenkins', 'At least he had chicken', undefined, 'e/e4/Leeroy-jenkins.png', AchievementType.Mercenary, undefined],
		145: ['Merc Life', 'Get a mercenary to level 5', undefined, undefined, '2/2e/Merc-achieve.png', AchievementType.Mercenary, { type: QuestTypes.mercMaxLevel, target: 5 }],
		146: ['Getting your money\'s worth', 'Get a mercenary to level 10', undefined, undefined, '2/2e/Merc-achieve.png', AchievementType.Mercenary, { type: QuestTypes.mercMaxLevel, target: 10 }],
		147: ['You\'re still alive?', 'Get a mercenary to level 15', undefined, undefined, '2/2e/Merc-achieve.png', AchievementType.Mercenary, { type: QuestTypes.mercMaxLevel, target: 15 }],
		148: ['Mercenary Champion', 'Get a mercenary to level 20', undefined, undefined, '2/2e/Merc-achieve.png', AchievementType.Mercenary, { type: QuestTypes.mercMaxLevel, target: 20 }],
		149: ['Exceptional Specimen', 'Get a mercenary to level 25', undefined, undefined, '2/2e/Merc-achieve.png', AchievementType.Mercenary, { type: QuestTypes.mercMaxLevel, target: 25 }],
		150: ['Recruit an Epic Mercenary', 'Recruit an Epic Mercenary.', undefined, undefined, '3/3f/Recruit-epic-merc.png', AchievementType.Mercenary, undefined],
		151: ['Team Leader', 'Have 5 mercenaries.', undefined, undefined, '0/00/Team-leader.png', AchievementType.Mercenary, undefined],
		152: ['Transcendent', 'Transcend.', undefined, undefined, '5/53/Transcend_achieve.png', AchievementType.Transcendence, undefined],
		153: ['Transcendent Zone Explorer', 'Beat Zone 4,000 after transcending', undefined, undefined, '4/4a/4kTrans_achie.png', AchievementType.Transcendence, { type: QuestTypes.beatZoneAfterTranscend, target: 4e3 }],
		154: ['Transcendent Zone Warrior', 'Beat Zone 5,000 after transcending', undefined, undefined, '4/4a/4kTrans_achie.png', AchievementType.Transcendence, { type: QuestTypes.beatZoneAfterTranscend, target: 5e3 }],
		155: ['Transcendent Zone Crusher', 'Beat Zone 7,500 after transcending', undefined, undefined, '5/58/Zone_7500_achieve.png', AchievementType.Transcendence, { type: QuestTypes.beatZoneAfterTranscend, target: 7.5e3 }],
		156: ['Transcendent Zone Connoisseur', 'Beat Zone 10,000 after transcending', undefined, undefined, '5/58/Zone_7500_achieve.png', AchievementType.Transcendence, { type: QuestTypes.beatZoneAfterTranscend, target: 1e4 }],
		157: ['Transcendent Zone Annihilator', 'Beat Zone 15,000 after transcending', undefined, undefined, '7/7d/Zone_15000_achieve.png', AchievementType.Transcendence, { type: QuestTypes.beatZoneAfterTranscend, target: 1.5e4 }],
		158: ['Transcendent Zone Devourer', 'Beat Zone 20,000 after transcending', undefined, undefined, '7/7d/Zone_15000_achieve.png', AchievementType.Transcendence, { type: QuestTypes.beatZoneAfterTranscend, target: 2e4 }],
		159: ['Transcendent Zone Conqueror', 'Beat Zone 30,000 after transcending', undefined, undefined, 'f/fb/30kTrans_achie.png', AchievementType.Transcendence, { type: QuestTypes.beatZoneAfterTranscend, target: 3e4 }],
		160: ['A Glimpse Outside', 'Acquire 50 Ancient Souls', undefined, undefined, '1/1c/AS_achie.png', AchievementType.Transcendence, { type: QuestTypes.AcquireAncientSouls, target: 50 }],
		161: ['Drinking Deep', 'Acquire 100 Ancient Souls', undefined, undefined, '1/1c/AS_achie.png', AchievementType.Transcendence, { type: QuestTypes.AcquireAncientSouls, target: 1e2 }],
		162: ['Ancient Crusher', 'Acquire 200 Ancient Souls', undefined, undefined, '1/1c/AS_achie.png', AchievementType.Transcendence, { type: QuestTypes.AcquireAncientSouls, target: 2e2 }],
		163: ['Traitor', 'Acquire 500 Ancient Souls', undefined, undefined, '1/1c/AS_achie.png', AchievementType.Transcendence, { type: QuestTypes.AcquireAncientSouls, target: 5e2 }],
		164: ['Transcendent Zone Vanquisher', 'Beat Zone 100,000 after transcending', undefined, undefined, 'f/fb/30kTrans_achie.png', AchievementType.Transcendence, { type: QuestTypes.beatZoneAfterTranscend, target: 1e5 }],
		165: ['Transcendent Zoneist', 'Beat Zone 250,000 after transcending', undefined, undefined, 'f/fb/30kTrans_achie.png', AchievementType.Transcendence, { type: QuestTypes.beatZoneAfterTranscend, target: 2.5e5 }],
		166: ['Point of No Return', 'Beat Zone 1,000,000 after transcending', undefined, undefined, 'f/fb/30kTrans_achie.png', AchievementType.Transcendence, { type: QuestTypes.beatZoneAfterTranscend, target: 1e6 }],
		167: ['Host of the Gate', 'Acquire 1000 Ancient Souls', undefined, undefined, '1/1c/AS_achie.png', AchievementType.Transcendence, { type: QuestTypes.AcquireAncientSouls, target: 1e3 }],
		168: ['Herald to the Void', 'Acquire 10000 Ancient Souls', undefined, undefined, '1/1c/AS_achie.png', AchievementType.Transcendence, { type: QuestTypes.AcquireAncientSouls, target: 1e4 }],
		169: ['Complicit to Ruin', 'Acquire 100000 Ancient Souls', undefined, undefined, '1/1c/AS_achie.png', AchievementType.Transcendence, { type: QuestTypes.AcquireAncientSouls, target: 1e5 }]
	}