const Heroes = {
	1: ['Cid, the Helpful Adventurer', 'heroes/normal/1.webp', 'heroes/gilded/1.webp'],
	2: ['Treebeast', 'heroes/normal/2.webp', 'heroes/gilded/2.webp'],
	3: ['Ivan, the Drunken Brawler', 'heroes/normal/3.webp', 'heroes/gilded/3.webp'],
	4: ['Brittany, Beach Princess', 'heroes/normal/4.webp', 'heroes/gilded/4.webp'],
	5: ['The Wandering Fisherman', 'heroes/normal/5.webp', 'heroes/gilded/5.webp'],
	6: ['Betty Clicker', 'heroes/normal/6.webp', 'heroes/gilded/6.webp'],
	7: ['The Masked Samurai', 'heroes/7samurai.webp'],
	8: ['Leon', 'heroes/leon.webp'],
	9: ['The Great Forest Seer', 'heroes/9forestseer.webp'],
	10: ['Alexa, Assassin', 'heroes/alexa.webp'],
	11: ['Natalia, Ice Apprentice', 'heroes/10natalia.webp'],
	12: ['Mercedes, Duchess of Blades', 'heroes/11mercedes.webp'],
	13: ['Bobby, Bounty Hunter', 'heroes/12bobby.webp'],
	14: ['Broyle Lindeoven, Fire Mage', 'heroes/13broyle.webp'],
	15: ["Sir George II, King's Guard", 'heroes/14sirgeorge.webp'],
	16: ['King Midas', 'heroes/15kingmidas.webp'],
	17: ['Referi Jerator, Ice Wizard', 'heroes/16referi.webp'],
	18: ['Abaddon', 'heroes/17abbadon.webp'],
	19: ['Ma Zhu', 'heroes/18mazhu.webp'],
	20: ['Amenhotep', 'heroes/19amenhotep.webp'],
	21: ['Beastlord', 'heroes/20beastlord.webp'],
	22: ['Athena, Goddess of War', 'heroes/athena.webp'],
	23: ['Aphrodite, Goddess of Love', 'heroes/22aphrodite.webp'],
	24: ['Shinatobe, Wind Deity', 'heroes/shinatobe.webp'],
	25: ['Grant, The General', 'heroes/grant.webp'],
	26: ['Frostleaf', 'heroes/frostleaf.webp'],
	27: ['Dread Knight', 'heroes/dread_knight.webp'],
	28: ['Atlas', 'heroes/atlas.webp'],
	29: ['Terra', 'heroes/terra.webp'],
	30: ['Phthalo', 'heroes/phthalo.webp'],
	31: ['Orntchya Gladeye, Didensy Banana', 'heroes/didensy.webp'],
	32: ['Lilin', 'heroes/lilin.webp'],
	33: ['Cadmia', 'heroes/cadmia.webp'],
	34: ['Alabaster', 'heroes/alabaster.webp'],
	35: ['Astraea', 'heroes/astraea.webp'],
	36: ['Chiron', 'heroes/chiron.webp'],
	37: ['Moloch', 'heroes/moloch.webp'],
	38: ['Bomber Max', 'heroes/bomber_max.webp'],
	39: ['Gog', 'heroes/gog.webp'],
	40: ['Wepwawet', 'heroes/wepwawet.webp'],
	41: ['Tsuchi', 'heroes/tsuchi.webp'],
	42: ['Skogur', 'heroes/skogur.webp'],
	43: ['Moeru', 'heroes/moeru.webp'],
	44: ['Zilar', 'heroes/zilar.webp'],
	45: ['Madzi', 'heroes/madzi.webp'],
	46: ['Xavira', 'heroes/xavira.webp'],
	47: ['Cadu, Tomb Guardian', 'heroes/cadu.webp'],
	48: ['Ceus, Tomb Guardian', 'heroes/ceus.webp'],
	49: ['The Maw', 'heroes/the_maw.webp'],
	50: ['Yachiyl, The Primordial Soul', 'heroes/yachiyl.webp'],
	51: ['Ace Scout Rose', 'heroes/ace_scout_rose.webp'],
	52: ['Ace Scout Sophia', 'heroes/ace_scout_sophia.webp'],
	53: ['Ace Scout Blanche', 'heroes/ace_scout_blanche.webp'],
	54: ['Ace Scout Dorothy', 'heroes/ace_scout_dorothy.webp']
};
