allowBuilds:
  core-js: true
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
minimumReleaseAgeExclude:
  - '@vercel/firewall@1.2.2'
  - posthog-js@1.407.5
  - resend@6.18.1
